name: Build Mujde apk for LSPosed
on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APK
        run: bash ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mujde-apk
          path: app/build/outputs/apk/debug/app-debug.apk
