name: Build Mujde apk for X×¤osed-framework

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build APK
        run: bash ./gradlew assembleRelease

      - name: Build AAB
        run: bash ./gradlew bundleRelease

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12'

      - name: Install signapp dependencies
        run: pip install -r requirements.txt && buildapp_fetch_tools

      - name: Sign apk
        working-directory: app/build/outputs/apk/release/
        run: signapp -a app-release-unsigned.apk -o app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mujde-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: mujde-aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Release Nightly
        uses: softprops/action-gh-release@v1
        with:
          body: Nightly Builds
          tag_name: github_run
          name: Action Release
          files: |
             app/build/outputs/apk/release/app-release.apk
             app/build/outputs/bundle/release/app-release.aab
