name: Build Mujde module

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # TODO: use dockerfile? (YES?)

    strategy:
      matrix:
        android-abi: [x86, armeabi-v7a, arm64-v8a]

    steps:
      - uses: actions/checkout@v3

    # TODO: is needed? (NO?)
    #   - uses: nttld/setup-ndk@v1
    #     with:
    #       ndk-version: r25c

    # TODO: build shared-lib/executable
    # TODO: copy lib to magisk tree, upload shared-lib
    # TODO: zip magisk tree, upload artifact
