name: Build Mujde apk for LSPosed

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APK
        working-directory: ./client
        run: bash ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mujde-apk
          path: client/app/build/outputs/apk/debug/app-debug.apk
